# NumPy

NumPy is the fundamental package for scientific computing with Python. It contains among other things:

- a powerful N-dimensional array object
- sophisticated (broadcasting) functions
- tools for integrating C/C++ and Fortran code
- useful linear algebra, Fourier transform, and random number capabilities

Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. Arbitrary data-types can be defined. This allows NumPy to seamlessly and speedily integrate with a wide variety of databases.

Library documentation: <a>http://www.numpy.org/</a>

Reference: <a>https://github.com/jdwittenauer/ipython-notebooks</a>

In [1]:
from numpy import *

In [2]:
# declare a vector using a list as the argument
v = array([1,2,3,4])
v

array([1, 2, 3, 4])

In [3]:
# declare a matrix using a nested list as the argument
M = array([[1,2],[3,4]])
M

array([[1, 2],
       [3, 4]])

In [4]:
# still the same core type with different shapes
type(v), type(M)

(numpy.ndarray, numpy.ndarray)

In [5]:
M.size

4

In [6]:
# arguments: start, stop, step
x = arange(0, 10, 1)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
linspace(0, 10, 25)

array([ 0.        ,  0.41666667,  0.83333333,  1.25      ,  1.66666667,
        2.08333333,  2.5       ,  2.91666667,  3.33333333,  3.75      ,
        4.16666667,  4.58333333,  5.        ,  5.41666667,  5.83333333,
        6.25      ,  6.66666667,  7.08333333,  7.5       ,  7.91666667,
        8.33333333,  8.75      ,  9.16666667,  9.58333333, 10.        ])

In [8]:
logspace(0, 10, 10, base=e)

array([1.00000000e+00, 3.03773178e+00, 9.22781435e+00, 2.80316249e+01,
       8.51525577e+01, 2.58670631e+02, 7.85771994e+02, 2.38696456e+03,
       7.25095809e+03, 2.20264658e+04])

In [9]:
x, y = mgrid[0:5, 0:5]
x

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

In [10]:
y

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [11]:
from numpy import random

In [12]:
random.rand(5,5)

array([[0.75148224, 0.59476055, 0.27068131, 0.0922317 , 0.03330407],
       [0.946728  , 0.38494146, 0.60690262, 0.21462463, 0.50061855],
       [0.19160879, 0.1558853 , 0.25559764, 0.50995617, 0.8040646 ],
       [0.61691613, 0.31366604, 0.58834983, 0.89459502, 0.31109243],
       [0.84504604, 0.33596414, 0.77301376, 0.18250637, 0.5914537 ]])

In [13]:
# normal distribution
random.randn(5,5)

array([[ 0.62936024, -0.48469606,  1.39505247,  1.23661901, -0.72600501],
       [ 0.3730929 , -0.07783467,  0.00285743, -0.5371118 ,  1.17894756],
       [ 1.42845203, -0.37902411, -0.33870307,  1.83079617, -1.66120354],
       [ 0.79578975,  0.65771848,  0.33185501, -1.85370979, -0.95989737],
       [-1.02171168, -0.06115196,  1.47291448,  0.50136862, -0.0827814 ]])

In [14]:
diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [15]:
M.itemsize

8

In [17]:
M.nbytes

32

In [17]:
M.ndim

2

In [18]:
v[0], M[1,1]

(1, 4)

In [19]:
M[1]

array([3, 4])

In [20]:
# assign new value
M[0,0] = 7
M

array([[7, 2],
       [3, 4]])

In [21]:
M[0,:] = 0
M

array([[0, 0],
       [3, 4]])

In [22]:
# slicing works just like with lists
A = array([1,2,3,4,5])
A[1:3]

array([2, 3])

In [23]:
A = array([[n+m*10 for n in range(5)] for m in range(5)])
A

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [24]:
row_indices = [1, 2, 3]
A[row_indices]

array([[10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

In [25]:
# index masking
B = array([n for n in range(5)])
row_mask = array([True, False, True, False, False])
B[row_mask]

array([0, 2])

### Linear Algebra

In [26]:
v1 = arange(0, 5)

In [27]:
v1 + 2

array([2, 3, 4, 5, 6])

In [28]:
v1 * 2

array([0, 2, 4, 6, 8])

In [29]:
v1 * v1

array([ 0,  1,  4,  9, 16])

In [30]:
dot(v1, v1)

30

In [31]:
dot(A, v1)

array([ 30, 130, 230, 330, 430])

In [32]:
# cast changes behavior of + - * etc. to use matrix algebra
M = matrix(A)
M * M

matrix([[ 300,  310,  320,  330,  340],
        [1300, 1360, 1420, 1480, 1540],
        [2300, 2410, 2520, 2630, 2740],
        [3300, 3460, 3620, 3780, 3940],
        [4300, 4510, 4720, 4930, 5140]])

In [33]:
# inner product
v.T * v

array([ 1,  4,  9, 16])

In [34]:
C = matrix([[1j, 2j], [3j, 4j]])
C

matrix([[0.+1.j, 0.+2.j],
        [0.+3.j, 0.+4.j]])

In [35]:
conjugate(C)

matrix([[0.-1.j, 0.-2.j],
        [0.-3.j, 0.-4.j]])

In [36]:
# inverse
C.I

matrix([[0.+2.j , 0.-1.j ],
        [0.-1.5j, 0.+0.5j]])

### Statistics

In [40]:
mean(A[:,3])

23.0

In [41]:
std(A[:,3]), var(A[:,3])

(14.142135623730951, 200.0)

In [42]:
A[:,3].min(), A[:,3].max()

(3, 43)

In [43]:
d = arange(1, 10)
sum(d), prod(d)

(45, 362880)

In [44]:
cumsum(d)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45])

In [45]:
cumprod(d)

array([     1,      2,      6,     24,    120,    720,   5040,  40320,
       362880])

In [46]:
# sum of diagonal
trace(A)

110

In [47]:
m = random.rand(3, 3)
m

array([[0.53135153, 0.30198026, 0.59776563],
       [0.61272092, 0.21393882, 0.43546586],
       [0.34654085, 0.64997346, 0.0587502 ]])

In [48]:
# use axis parameter to specify how function behaves
m.max(), m.max(axis=0)

(0.6499734610941185, array([0.61272092, 0.64997346, 0.59776563]))

In [49]:
A

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [50]:
# reshape without copying underlying data
n, m = A.shape
B = A.reshape((1,n*m))

B

array([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14, 20, 21, 22, 23, 24, 30,
        31, 32, 33, 34, 40, 41, 42, 43, 44]])

In [51]:
# modify the array
B[0,0:5] = 5
B

array([[ 5,  5,  5,  5,  5, 10, 11, 12, 13, 14, 20, 21, 22, 23, 24, 30,
        31, 32, 33, 34, 40, 41, 42, 43, 44]])

In [52]:
# also changed
A

array([[ 5,  5,  5,  5,  5],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [53]:
# creates a copy
B = A.flatten()
B

array([ 5,  5,  5,  5,  5, 10, 11, 12, 13, 14, 20, 21, 22, 23, 24, 30, 31,
       32, 33, 34, 40, 41, 42, 43, 44])

In [54]:
# can insert a dimension in an array
v = array([1,2,3])
v[:, newaxis], v[:,newaxis].shape, v[newaxis,:].shape

(array([[1],
        [2],
        [3]]),
 (3, 1),
 (1, 3))

In [55]:
repeat(v, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [56]:
tile(v, 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [57]:
w = array([5, 6])

In [58]:
concatenate((v, w), axis=0)

array([1, 2, 3, 5, 6])

In [59]:
# deep copy
B = copy(A)